services:
  nats:
    container_name: nats
    # https://github.com/bmcustodio/docker-compose-nats-cluster/tree/master
    # https://docs.nats.io/running-a-nats-service/nats_docker#creating-a-nats-cluster-with-docker-compose
    image: nats:latest
    # ports:
    #   - "4222:4222"  # NATS server port
  memcached:
    container_name: memcached
    image: memcached:latest
    
  data-scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile.data-scraper
    image: data-scraper
    container_name: data-scraper
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
  
  bog-currency-rate:
    build:
      context: .
      dockerfile: docker/Dockerfile.bog-currency-rate
    image: bog-currency-rate
    container_name: bog-currency-rate
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  telegram-connector:
    build:
      context: .
      dockerfile: docker/Dockerfile.telegram-connector
    image: telegram-connector
    container_name: telegram-connector
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      # - data-scraper
      - bog-currency-rate