FROM golang:1.23-alpine

RUN mkdir /app

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

ADD . /app

RUN go env -w GOCACHE=/go-cache
RUN --mount=type=cache,target=/gomod-cache
RUN --mount=type=cache,target=/gomod-cache --mount=type=cache,target=/go-cache go build -o bog-currency-rate cmd/bog-currency-rate/main.go

CMD ["/app/bog-currency-rate"]