FROM golang:1.23-alpine

RUN mkdir /app

ADD . /app

WORKDIR /app

RUN go env -w GOCACHE=/go-cache
RUN --mount=type=cache,target=/gomod-cache
RUN --mount=type=cache,target=/gomod-cache --mount=type=cache,target=/go-cache go build -o data-scraper cmd/scraper/main.go

CMD ["/app/data-scraper"]